feat: Personal Space , Sessions Dashboard , Log out
poorman-tools/poorman-tools-dashboard pull request #2
Opened 2024-12-02 07:06 UTC by avevotsira

2024-12-02 07:07 UTC, avevotsira commented
![image](https://github.com/user-attachments/assets/70027218-5b10-4cd7-9f16-fc74d4ea54f5)
![image](https://github.com/user-attachments/assets/62d904e7-add3-49e8-afe4-90ce3137b613)

2024-12-02 14:31 UTC, invisal requested changes

2024-12-02 14:31 UTC, invisal commented on src/app/(session)/sessions/page.tsx
> +  );
It is better to follow our current pattern of using hook. Like `useSessionList()`

2024-12-02 14:31 UTC, invisal commented on src/components/containers/personal-container.tsx
> +  };
Can we turn it into a hook like ```useRevokeToken```

2024-12-03 10:46 UTC, invisal approved these changes
LGTM

2024-12-03 10:46 UTC, merged